# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wymjarex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='belt',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='wpis',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='wpis',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='wpis',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
