# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wymjarex', '0002_auto_20161027_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpis',
            name='belt',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='wpis',
            name='created_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='wpis',
            name='waist',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='wpis',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
