# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wymjarex', '0003_auto_20161104_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wpis',
            new_name='Post',
        ),
    ]
